apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-mcs1-machine-sensor

resources:
- machine-sensor-namespace.yaml
- machine-sensor-1-deployment.yaml

configMapGenerator:
- name: machine-sensor-1
  env: machine-sensor-1-configmap.properties
  behavior: create

images:
- name: machine-sensor
  newName: quay.io/manuela/iot-software-sensor
  newTag: quickstart



