apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: manuela-mcs-gitops-channel
  namespace: manuela-mcs1
spec:
  type: GitHub
  pathname: https://github.com/stefan-bergstein/manuela-gitops-multicluster-subscription-operator.git


